# Generated by Django 4.2.3 on 2023-07-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=50, verbose_name='카테고리'),
        ),
    ]
